title: Continental
description: Sharing thoughts and experiences

url: "https://continentaldontmindifido.github.io"
baseurl: ""

remote_theme: pages-themes/minimal

plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md

show_downloads: false